version: '3.9'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  weather-api:
    build: .
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_PLAYGROUND_ENABLE: ${SERVER_PLAYGROUND_ENABLE}
      REDIS_ADDRESS: ${REDIS_ADDRESS}
      EXPIRATION_WEATHER_INFO: ${EXPIRATION_WEATHER_INFO}
      API_KEY_ACCU_WEATHER: ${API_KEY_ACCU_WEATHER}
      API_KEY_OPEN_WEATHER: ${API_KEY_OPEN_WEATHER}
      API_KEY_API_NINJAS: ${API_KEY_API_NINJAS}
    ports:
      - '8080:8080'