// Code generated by MockGen. DO NOT EDIT.
// Source: provider/provider.go
//
// Generated by this command:
//
//	mockgen -source provider/provider.go -destination provider/mock/provider_mock.go
//

// Package mock_provider is a generated GoMock package.
package mock_provider

import (
	reflect "reflect"
	dto "weather-api/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockLocalityProvider is a mock of LocalityProvider interface.
type MockLocalityProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLocalityProviderMockRecorder
}

// MockLocalityProviderMockRecorder is the mock recorder for MockLocalityProvider.
type MockLocalityProviderMockRecorder struct {
	mock *MockLocalityProvider
}

// NewMockLocalityProvider creates a new mock instance.
func NewMockLocalityProvider(ctrl *gomock.Controller) *MockLocalityProvider {
	mock := &MockLocalityProvider{ctrl: ctrl}
	mock.recorder = &MockLocalityProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalityProvider) EXPECT() *MockLocalityProviderMockRecorder {
	return m.recorder
}

// GetCityName mocks base method.
func (m *MockLocalityProvider) GetCityName(latitude, longitude float64) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityName", latitude, longitude)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityName indicates an expected call of GetCityName.
func (mr *MockLocalityProviderMockRecorder) GetCityName(latitude, longitude any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityName", reflect.TypeOf((*MockLocalityProvider)(nil).GetCityName), latitude, longitude)
}

// GetLocalityDto mocks base method.
func (m *MockLocalityProvider) GetLocalityDto(cityName string) (*dto.LocalityDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalityDto", cityName)
	ret0, _ := ret[0].(*dto.LocalityDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalityDto indicates an expected call of GetLocalityDto.
func (mr *MockLocalityProviderMockRecorder) GetLocalityDto(cityName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalityDto", reflect.TypeOf((*MockLocalityProvider)(nil).GetLocalityDto), cityName)
}

// MockWeatherProvider is a mock of WeatherProvider interface.
type MockWeatherProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherProviderMockRecorder
}

// MockWeatherProviderMockRecorder is the mock recorder for MockWeatherProvider.
type MockWeatherProviderMockRecorder struct {
	mock *MockWeatherProvider
}

// NewMockWeatherProvider creates a new mock instance.
func NewMockWeatherProvider(ctrl *gomock.Controller) *MockWeatherProvider {
	mock := &MockWeatherProvider{ctrl: ctrl}
	mock.recorder = &MockWeatherProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherProvider) EXPECT() *MockWeatherProviderMockRecorder {
	return m.recorder
}

// CurrentWeatherInfo mocks base method.
func (m *MockWeatherProvider) CurrentWeatherInfo(weatherRequestDto dto.WeatherRequestDto) *dto.CurrentWeatherDto {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentWeatherInfo", weatherRequestDto)
	ret0, _ := ret[0].(*dto.CurrentWeatherDto)
	return ret0
}

// CurrentWeatherInfo indicates an expected call of CurrentWeatherInfo.
func (mr *MockWeatherProviderMockRecorder) CurrentWeatherInfo(weatherRequestDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentWeatherInfo", reflect.TypeOf((*MockWeatherProvider)(nil).CurrentWeatherInfo), weatherRequestDto)
}

// DailyWeatherInfo mocks base method.
func (m *MockWeatherProvider) DailyWeatherInfo(weatherRequestDto dto.WeatherRequestDto) *[]dto.DailyWeatherDto {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DailyWeatherInfo", weatherRequestDto)
	ret0, _ := ret[0].(*[]dto.DailyWeatherDto)
	return ret0
}

// DailyWeatherInfo indicates an expected call of DailyWeatherInfo.
func (mr *MockWeatherProviderMockRecorder) DailyWeatherInfo(weatherRequestDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DailyWeatherInfo", reflect.TypeOf((*MockWeatherProvider)(nil).DailyWeatherInfo), weatherRequestDto)
}

// HourlyWeatherInfo mocks base method.
func (m *MockWeatherProvider) HourlyWeatherInfo(weatherRequestDto dto.WeatherRequestDto) *[]dto.HourlyWeatherDto {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HourlyWeatherInfo", weatherRequestDto)
	ret0, _ := ret[0].(*[]dto.HourlyWeatherDto)
	return ret0
}

// HourlyWeatherInfo indicates an expected call of HourlyWeatherInfo.
func (mr *MockWeatherProviderMockRecorder) HourlyWeatherInfo(weatherRequestDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HourlyWeatherInfo", reflect.TypeOf((*MockWeatherProvider)(nil).HourlyWeatherInfo), weatherRequestDto)
}

// MockSaveInfoProvider is a mock of SaveInfoProvider interface.
type MockSaveInfoProvider[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockSaveInfoProviderMockRecorder[T]
}

// MockSaveInfoProviderMockRecorder is the mock recorder for MockSaveInfoProvider.
type MockSaveInfoProviderMockRecorder[T any] struct {
	mock *MockSaveInfoProvider[T]
}

// NewMockSaveInfoProvider creates a new mock instance.
func NewMockSaveInfoProvider[T any](ctrl *gomock.Controller) *MockSaveInfoProvider[T] {
	mock := &MockSaveInfoProvider[T]{ctrl: ctrl}
	mock.recorder = &MockSaveInfoProviderMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaveInfoProvider[T]) EXPECT() *MockSaveInfoProviderMockRecorder[T] {
	return m.recorder
}

// Save mocks base method.
func (m *MockSaveInfoProvider[T]) Save(info T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", info)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSaveInfoProviderMockRecorder[T]) Save(info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSaveInfoProvider[T])(nil).Save), info)
}
