// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -destination=mock/provider.go
//

// Package mock_provider is a generated GoMock package.
package mock_provider

import (
	context "context"
	reflect "reflect"

	dto "github.com/shredd0r/weather-api/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockWeatherProvider is a mock of WeatherProvider interface.
type MockWeatherProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherProviderMockRecorder
}

// MockWeatherProviderMockRecorder is the mock recorder for MockWeatherProvider.
type MockWeatherProviderMockRecorder struct {
	mock *MockWeatherProvider
}

// NewMockWeatherProvider creates a new mock instance.
func NewMockWeatherProvider(ctrl *gomock.Controller) *MockWeatherProvider {
	mock := &MockWeatherProvider{ctrl: ctrl}
	mock.recorder = &MockWeatherProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherProvider) EXPECT() *MockWeatherProviderMockRecorder {
	return m.recorder
}

// CurrentWeather mocks base method.
func (m *MockWeatherProvider) CurrentWeather(ctx context.Context, request *dto.WeatherRequestProvider) (*dto.CurrentWeather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentWeather", ctx, request)
	ret0, _ := ret[0].(*dto.CurrentWeather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentWeather indicates an expected call of CurrentWeather.
func (mr *MockWeatherProviderMockRecorder) CurrentWeather(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentWeather", reflect.TypeOf((*MockWeatherProvider)(nil).CurrentWeather), ctx, request)
}

// DailyWeather mocks base method.
func (m *MockWeatherProvider) DailyWeather(ctx context.Context, request *dto.WeatherRequestProvider) (*[]*dto.DailyWeather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DailyWeather", ctx, request)
	ret0, _ := ret[0].(*[]*dto.DailyWeather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DailyWeather indicates an expected call of DailyWeather.
func (mr *MockWeatherProviderMockRecorder) DailyWeather(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DailyWeather", reflect.TypeOf((*MockWeatherProvider)(nil).DailyWeather), ctx, request)
}

// HourlyWeather mocks base method.
func (m *MockWeatherProvider) HourlyWeather(ctx context.Context, request *dto.WeatherRequestProvider) (*[]*dto.HourlyWeather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HourlyWeather", ctx, request)
	ret0, _ := ret[0].(*[]*dto.HourlyWeather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HourlyWeather indicates an expected call of HourlyWeather.
func (mr *MockWeatherProviderMockRecorder) HourlyWeather(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HourlyWeather", reflect.TypeOf((*MockWeatherProvider)(nil).HourlyWeather), ctx, request)
}

// MockLocationProvider is a mock of LocationProvider interface.
type MockLocationProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLocationProviderMockRecorder
}

// MockLocationProviderMockRecorder is the mock recorder for MockLocationProvider.
type MockLocationProviderMockRecorder struct {
	mock *MockLocationProvider
}

// NewMockLocationProvider creates a new mock instance.
func NewMockLocationProvider(ctrl *gomock.Controller) *MockLocationProvider {
	mock := &MockLocationProvider{ctrl: ctrl}
	mock.recorder = &MockLocationProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationProvider) EXPECT() *MockLocationProviderMockRecorder {
	return m.recorder
}

// FindGeocoding mocks base method.
func (m *MockLocationProvider) FindGeocoding(ctx context.Context, request *dto.GeocodingRequest) (*[]*dto.Geocoding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGeocoding", ctx, request)
	ret0, _ := ret[0].(*[]*dto.Geocoding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindGeocoding indicates an expected call of FindGeocoding.
func (mr *MockLocationProviderMockRecorder) FindGeocoding(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGeocoding", reflect.TypeOf((*MockLocationProvider)(nil).FindGeocoding), ctx, request)
}

// GetAddressHashByCoords mocks base method.
func (m *MockLocationProvider) GetAddressHashByCoords(ctx context.Context, coords *dto.Coords) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressHashByCoords", ctx, coords)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressHashByCoords indicates an expected call of GetAddressHashByCoords.
func (mr *MockLocationProviderMockRecorder) GetAddressHashByCoords(ctx, coords any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressHashByCoords", reflect.TypeOf((*MockLocationProvider)(nil).GetAddressHashByCoords), ctx, coords)
}

// LocationByAddressHash mocks base method.
func (m *MockLocationProvider) LocationByAddressHash(ctx context.Context, coords *dto.Coords, addressHash string) (*dto.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocationByAddressHash", ctx, coords, addressHash)
	ret0, _ := ret[0].(*dto.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LocationByAddressHash indicates an expected call of LocationByAddressHash.
func (mr *MockLocationProviderMockRecorder) LocationByAddressHash(ctx, coords, addressHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocationByAddressHash", reflect.TypeOf((*MockLocationProvider)(nil).LocationByAddressHash), ctx, coords, addressHash)
}
