package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"

	"github.com/shredd0r/weather-api/graph/model"
)

// FindGeocoding is the resolver for the findGeocoding field.
func (r *queryResolver) FindGeocoding(ctx context.Context, input *model.GeocodingRequest) ([]*model.Geocoding, error) {
	resp, err := r.GraphqlApi.FindGeocoding(ctx, input)

	if err != nil {
		return nil, err
	}

	return *resp, nil
}

// CurrentWeather is the resolver for the currentWeather field.
func (r *queryResolver) CurrentWeather(ctx context.Context, input *model.WeatherRequest) (*model.CurrentWeather, error) {
	return r.GraphqlApi.CurrentWeather(ctx, input)
}

// HourlyWeather is the resolver for the hourlyWeather field.
func (r *queryResolver) HourlyWeather(ctx context.Context, input *model.WeatherRequest) ([]*model.HourlyWeather, error) {
	resp, err := r.GraphqlApi.HourlyWeather(ctx, input)

	if err != nil {
		return nil, err
	}

	return *resp, nil
}

// DailyWeather is the resolver for the dailyWeather field.
func (r *queryResolver) DailyWeather(ctx context.Context, input *model.WeatherRequest) ([]*model.DailyWeather, error) {
	resp, err := r.GraphqlApi.DailyWeather(ctx, input)

	if err != nil {
		return nil, err
	}

	return *resp, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
