// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/shredd0r/weather-api/dto"
)

type Coords struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type CurrentWeather struct {
	EpochTime            int64          `json:"epochTime"`
	Visibility           *float64       `json:"visibility,omitempty"`
	CurrentTemperature   *float64       `json:"currentTemperature,omitempty"`
	MinTemperature       *float64       `json:"minTemperature,omitempty"`
	MaxTemperature       *float64       `json:"maxTemperature,omitempty"`
	FeelsLikeTemperature *float64       `json:"feelsLikeTemperature,omitempty"`
	WeatherID            *dto.WeatherId `json:"weatherId,omitempty"`
	MobileLink           string         `json:"mobileLink"`
	Link                 string         `json:"link"`
}

type DailyWeather struct {
	EpochTime                  int64                 `json:"epochTime"`
	MinTemperature             *float64              `json:"minTemperature,omitempty"`
	MaxTemperature             *float64              `json:"maxTemperature,omitempty"`
	Humidity                   float64               `json:"humidity"`
	UvIndex                    *float64              `json:"uvIndex,omitempty"`
	SunriseTime                int64                 `json:"sunriseTime"`
	SunsetTime                 int64                 `json:"SunsetTime"`
	Wind                       *Wind                 `json:"wind,omitempty"`
	ProbabilityOfPrecipitation *float64              `json:"probabilityOfPrecipitation,omitempty"`
	PrecipitationType          dto.PrecipitationType `json:"precipitationType"`
	WeatherID                  *dto.WeatherId        `json:"weatherId,omitempty"`
	MobileLink                 string                `json:"mobileLink"`
	Link                       string                `json:"link"`
}

type Geocoding struct {
	Name      string  `json:"name"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Country   string  `json:"country"`
	State     string  `json:"state"`
}

type GeocodingRequest struct {
	City    *string `json:"City,omitempty"`
	State   *string `json:"State,omitempty"`
	Country *string `json:"Country,omitempty"`
}

type HourlyWeather struct {
	EpochTime                  int64                 `json:"epochTime"`
	CurrentTemperature         *float64              `json:"currentTemperature,omitempty"`
	FeelsLikeTemperature       *float64              `json:"feelsLikeTemperature,omitempty"`
	UvIndex                    *float64              `json:"uvIndex,omitempty"`
	ProbabilityOfPrecipitation *float64              `json:"probabilityOfPrecipitation,omitempty"`
	PrecipitationType          dto.PrecipitationType `json:"precipitationType"`
	AmountOfPrecipitation      *float64              `json:"amountOfPrecipitation,omitempty"`
	Wind                       *Wind                 `json:"wind,omitempty"`
	WeatherID                  *dto.WeatherId        `json:"weatherId,omitempty"`
	MobileLink                 string                `json:"mobileLink"`
	Link                       string                `json:"link"`
}

type Query struct {
}

type WeatherRequest struct {
	Coords     *Coords               `json:"coords"`
	Locale     string                `json:"locale"`
	Unit       dto.Unit              `json:"unit"`
	Forecaster dto.WeatherForecaster `json:"forecaster"`
}

type Wind struct {
	Speed   *float64 `json:"speed,omitempty"`
	Degrees float64  `json:"degrees"`
}
