// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mock/storage.go
//

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	context "context"
	reflect "reflect"

	dto "github.com/shredd0r/weather-api/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockWeatherStorage is a mock of WeatherStorage interface.
type MockWeatherStorage struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherStorageMockRecorder
}

// MockWeatherStorageMockRecorder is the mock recorder for MockWeatherStorage.
type MockWeatherStorageMockRecorder struct {
	mock *MockWeatherStorage
}

// NewMockWeatherStorage creates a new mock instance.
func NewMockWeatherStorage(ctrl *gomock.Controller) *MockWeatherStorage {
	mock := &MockWeatherStorage{ctrl: ctrl}
	mock.recorder = &MockWeatherStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherStorage) EXPECT() *MockWeatherStorageMockRecorder {
	return m.recorder
}

// GetAllLastTimeUpdatedCurrentWeather mocks base method.
func (m *MockWeatherStorage) GetAllLastTimeUpdatedCurrentWeather(ctx context.Context, forecaster dto.WeatherForecaster) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLastTimeUpdatedCurrentWeather", ctx, forecaster)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLastTimeUpdatedCurrentWeather indicates an expected call of GetAllLastTimeUpdatedCurrentWeather.
func (mr *MockWeatherStorageMockRecorder) GetAllLastTimeUpdatedCurrentWeather(ctx, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLastTimeUpdatedCurrentWeather", reflect.TypeOf((*MockWeatherStorage)(nil).GetAllLastTimeUpdatedCurrentWeather), ctx, forecaster)
}

// GetAllLastTimeUpdatedDailyWeather mocks base method.
func (m *MockWeatherStorage) GetAllLastTimeUpdatedDailyWeather(ctx context.Context, forecaster dto.WeatherForecaster) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLastTimeUpdatedDailyWeather", ctx, forecaster)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLastTimeUpdatedDailyWeather indicates an expected call of GetAllLastTimeUpdatedDailyWeather.
func (mr *MockWeatherStorageMockRecorder) GetAllLastTimeUpdatedDailyWeather(ctx, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLastTimeUpdatedDailyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).GetAllLastTimeUpdatedDailyWeather), ctx, forecaster)
}

// GetAllLastTimeUpdatedHourlyWeather mocks base method.
func (m *MockWeatherStorage) GetAllLastTimeUpdatedHourlyWeather(ctx context.Context, forecaster dto.WeatherForecaster) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLastTimeUpdatedHourlyWeather", ctx, forecaster)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLastTimeUpdatedHourlyWeather indicates an expected call of GetAllLastTimeUpdatedHourlyWeather.
func (mr *MockWeatherStorageMockRecorder) GetAllLastTimeUpdatedHourlyWeather(ctx, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLastTimeUpdatedHourlyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).GetAllLastTimeUpdatedHourlyWeather), ctx, forecaster)
}

// GetCurrentWeather mocks base method.
func (m *MockWeatherStorage) GetCurrentWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster) (*dto.CurrentWeather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentWeather", ctx, addressHash, forecaster)
	ret0, _ := ret[0].(*dto.CurrentWeather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentWeather indicates an expected call of GetCurrentWeather.
func (mr *MockWeatherStorageMockRecorder) GetCurrentWeather(ctx, addressHash, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentWeather", reflect.TypeOf((*MockWeatherStorage)(nil).GetCurrentWeather), ctx, addressHash, forecaster)
}

// GetDailyWeather mocks base method.
func (m *MockWeatherStorage) GetDailyWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster) (*[]*dto.DailyWeather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyWeather", ctx, addressHash, forecaster)
	ret0, _ := ret[0].(*[]*dto.DailyWeather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyWeather indicates an expected call of GetDailyWeather.
func (mr *MockWeatherStorageMockRecorder) GetDailyWeather(ctx, addressHash, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).GetDailyWeather), ctx, addressHash, forecaster)
}

// GetHourlyWeather mocks base method.
func (m *MockWeatherStorage) GetHourlyWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster) (*[]*dto.HourlyWeather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHourlyWeather", ctx, addressHash, forecaster)
	ret0, _ := ret[0].(*[]*dto.HourlyWeather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHourlyWeather indicates an expected call of GetHourlyWeather.
func (mr *MockWeatherStorageMockRecorder) GetHourlyWeather(ctx, addressHash, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHourlyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).GetHourlyWeather), ctx, addressHash, forecaster)
}

// RemoveCurrentWeather mocks base method.
func (m *MockWeatherStorage) RemoveCurrentWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCurrentWeather", ctx, addressHash, forecaster)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCurrentWeather indicates an expected call of RemoveCurrentWeather.
func (mr *MockWeatherStorageMockRecorder) RemoveCurrentWeather(ctx, addressHash, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCurrentWeather", reflect.TypeOf((*MockWeatherStorage)(nil).RemoveCurrentWeather), ctx, addressHash, forecaster)
}

// RemoveDailyWeather mocks base method.
func (m *MockWeatherStorage) RemoveDailyWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDailyWeather", ctx, addressHash, forecaster)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDailyWeather indicates an expected call of RemoveDailyWeather.
func (mr *MockWeatherStorageMockRecorder) RemoveDailyWeather(ctx, addressHash, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDailyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).RemoveDailyWeather), ctx, addressHash, forecaster)
}

// RemoveHourlyWeather mocks base method.
func (m *MockWeatherStorage) RemoveHourlyWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveHourlyWeather", ctx, addressHash, forecaster)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveHourlyWeather indicates an expected call of RemoveHourlyWeather.
func (mr *MockWeatherStorageMockRecorder) RemoveHourlyWeather(ctx, addressHash, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHourlyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).RemoveHourlyWeather), ctx, addressHash, forecaster)
}

// RemoveLastTimeUpdatedCurrentWeather mocks base method.
func (m *MockWeatherStorage) RemoveLastTimeUpdatedCurrentWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLastTimeUpdatedCurrentWeather", ctx, addressHash, forecaster)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLastTimeUpdatedCurrentWeather indicates an expected call of RemoveLastTimeUpdatedCurrentWeather.
func (mr *MockWeatherStorageMockRecorder) RemoveLastTimeUpdatedCurrentWeather(ctx, addressHash, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLastTimeUpdatedCurrentWeather", reflect.TypeOf((*MockWeatherStorage)(nil).RemoveLastTimeUpdatedCurrentWeather), ctx, addressHash, forecaster)
}

// RemoveLastTimeUpdatedDailyWeather mocks base method.
func (m *MockWeatherStorage) RemoveLastTimeUpdatedDailyWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLastTimeUpdatedDailyWeather", ctx, addressHash, forecaster)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLastTimeUpdatedDailyWeather indicates an expected call of RemoveLastTimeUpdatedDailyWeather.
func (mr *MockWeatherStorageMockRecorder) RemoveLastTimeUpdatedDailyWeather(ctx, addressHash, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLastTimeUpdatedDailyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).RemoveLastTimeUpdatedDailyWeather), ctx, addressHash, forecaster)
}

// RemoveLastTimeUpdatedHourlyWeather mocks base method.
func (m *MockWeatherStorage) RemoveLastTimeUpdatedHourlyWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLastTimeUpdatedHourlyWeather", ctx, addressHash, forecaster)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLastTimeUpdatedHourlyWeather indicates an expected call of RemoveLastTimeUpdatedHourlyWeather.
func (mr *MockWeatherStorageMockRecorder) RemoveLastTimeUpdatedHourlyWeather(ctx, addressHash, forecaster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLastTimeUpdatedHourlyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).RemoveLastTimeUpdatedHourlyWeather), ctx, addressHash, forecaster)
}

// SaveCurrentWeather mocks base method.
func (m *MockWeatherStorage) SaveCurrentWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster, weather dto.CurrentWeather) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCurrentWeather", ctx, addressHash, forecaster, weather)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCurrentWeather indicates an expected call of SaveCurrentWeather.
func (mr *MockWeatherStorageMockRecorder) SaveCurrentWeather(ctx, addressHash, forecaster, weather any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCurrentWeather", reflect.TypeOf((*MockWeatherStorage)(nil).SaveCurrentWeather), ctx, addressHash, forecaster, weather)
}

// SaveDailyWeather mocks base method.
func (m *MockWeatherStorage) SaveDailyWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster, weather []*dto.DailyWeather) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDailyWeather", ctx, addressHash, forecaster, weather)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDailyWeather indicates an expected call of SaveDailyWeather.
func (mr *MockWeatherStorageMockRecorder) SaveDailyWeather(ctx, addressHash, forecaster, weather any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDailyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).SaveDailyWeather), ctx, addressHash, forecaster, weather)
}

// SaveHourlyWeather mocks base method.
func (m *MockWeatherStorage) SaveHourlyWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster, weather []*dto.HourlyWeather) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveHourlyWeather", ctx, addressHash, forecaster, weather)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveHourlyWeather indicates an expected call of SaveHourlyWeather.
func (mr *MockWeatherStorageMockRecorder) SaveHourlyWeather(ctx, addressHash, forecaster, weather any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveHourlyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).SaveHourlyWeather), ctx, addressHash, forecaster, weather)
}

// SaveUpdatedTimeCurrentWeather mocks base method.
func (m *MockWeatherStorage) SaveUpdatedTimeCurrentWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster, lastTime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUpdatedTimeCurrentWeather", ctx, addressHash, forecaster, lastTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUpdatedTimeCurrentWeather indicates an expected call of SaveUpdatedTimeCurrentWeather.
func (mr *MockWeatherStorageMockRecorder) SaveUpdatedTimeCurrentWeather(ctx, addressHash, forecaster, lastTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUpdatedTimeCurrentWeather", reflect.TypeOf((*MockWeatherStorage)(nil).SaveUpdatedTimeCurrentWeather), ctx, addressHash, forecaster, lastTime)
}

// SaveUpdatedTimeDailyWeather mocks base method.
func (m *MockWeatherStorage) SaveUpdatedTimeDailyWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster, lastTime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUpdatedTimeDailyWeather", ctx, addressHash, forecaster, lastTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUpdatedTimeDailyWeather indicates an expected call of SaveUpdatedTimeDailyWeather.
func (mr *MockWeatherStorageMockRecorder) SaveUpdatedTimeDailyWeather(ctx, addressHash, forecaster, lastTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUpdatedTimeDailyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).SaveUpdatedTimeDailyWeather), ctx, addressHash, forecaster, lastTime)
}

// SaveUpdatedTimeHourlyWeather mocks base method.
func (m *MockWeatherStorage) SaveUpdatedTimeHourlyWeather(ctx context.Context, addressHash string, forecaster dto.WeatherForecaster, lastTime int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUpdatedTimeHourlyWeather", ctx, addressHash, forecaster, lastTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUpdatedTimeHourlyWeather indicates an expected call of SaveUpdatedTimeHourlyWeather.
func (mr *MockWeatherStorageMockRecorder) SaveUpdatedTimeHourlyWeather(ctx, addressHash, forecaster, lastTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUpdatedTimeHourlyWeather", reflect.TypeOf((*MockWeatherStorage)(nil).SaveUpdatedTimeHourlyWeather), ctx, addressHash, forecaster, lastTime)
}

// MockLocationStorage is a mock of LocationStorage interface.
type MockLocationStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLocationStorageMockRecorder
}

// MockLocationStorageMockRecorder is the mock recorder for MockLocationStorage.
type MockLocationStorageMockRecorder struct {
	mock *MockLocationStorage
}

// NewMockLocationStorage creates a new mock instance.
func NewMockLocationStorage(ctrl *gomock.Controller) *MockLocationStorage {
	mock := &MockLocationStorage{ctrl: ctrl}
	mock.recorder = &MockLocationStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationStorage) EXPECT() *MockLocationStorageMockRecorder {
	return m.recorder
}

// AddCoords mocks base method.
func (m *MockLocationStorage) AddCoords(ctx context.Context, coords *dto.Coords, addressHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCoords", ctx, coords, addressHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCoords indicates an expected call of AddCoords.
func (mr *MockLocationStorageMockRecorder) AddCoords(ctx, coords, addressHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCoords", reflect.TypeOf((*MockLocationStorage)(nil).AddCoords), ctx, coords, addressHash)
}

// GetAddressHashByCoords mocks base method.
func (m *MockLocationStorage) GetAddressHashByCoords(ctx context.Context, coords *dto.Coords) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressHashByCoords", ctx, coords)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddressHashByCoords indicates an expected call of GetAddressHashByCoords.
func (mr *MockLocationStorageMockRecorder) GetAddressHashByCoords(ctx, coords any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressHashByCoords", reflect.TypeOf((*MockLocationStorage)(nil).GetAddressHashByCoords), ctx, coords)
}

// GetAllLastTimeUseCoords mocks base method.
func (m *MockLocationStorage) GetAllLastTimeUseCoords(ctx context.Context) (map[dto.Coords]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLastTimeUseCoords", ctx)
	ret0, _ := ret[0].(map[dto.Coords]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLastTimeUseCoords indicates an expected call of GetAllLastTimeUseCoords.
func (mr *MockLocationStorageMockRecorder) GetAllLastTimeUseCoords(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLastTimeUseCoords", reflect.TypeOf((*MockLocationStorage)(nil).GetAllLastTimeUseCoords), ctx)
}

// GetLocation mocks base method.
func (m *MockLocationStorage) GetLocation(ctx context.Context, addressHash string) (*dto.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocation", ctx, addressHash)
	ret0, _ := ret[0].(*dto.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocation indicates an expected call of GetLocation.
func (mr *MockLocationStorageMockRecorder) GetLocation(ctx, addressHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocation", reflect.TypeOf((*MockLocationStorage)(nil).GetLocation), ctx, addressHash)
}

// RemoveCoords mocks base method.
func (m *MockLocationStorage) RemoveCoords(ctx context.Context, coords *dto.Coords) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCoords", ctx, coords)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCoords indicates an expected call of RemoveCoords.
func (mr *MockLocationStorageMockRecorder) RemoveCoords(ctx, coords any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCoords", reflect.TypeOf((*MockLocationStorage)(nil).RemoveCoords), ctx, coords)
}

// SaveLocation mocks base method.
func (m *MockLocationStorage) SaveLocation(ctx context.Context, location dto.Location, addressHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLocation", ctx, location, addressHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLocation indicates an expected call of SaveLocation.
func (mr *MockLocationStorageMockRecorder) SaveLocation(ctx, location, addressHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLocation", reflect.TypeOf((*MockLocationStorage)(nil).SaveLocation), ctx, location, addressHash)
}

// UpdateLastTimeUseCoords mocks base method.
func (m *MockLocationStorage) UpdateLastTimeUseCoords(ctx context.Context, coords *dto.Coords, time int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastTimeUseCoords", ctx, coords, time)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastTimeUseCoords indicates an expected call of UpdateLastTimeUseCoords.
func (mr *MockLocationStorageMockRecorder) UpdateLastTimeUseCoords(ctx, coords, time any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastTimeUseCoords", reflect.TypeOf((*MockLocationStorage)(nil).UpdateLastTimeUseCoords), ctx, coords, time)
}
