// Code generated by MockGen. DO NOT EDIT.
// Source: client/http/accu_weather_client.go
//
// Generated by this command:
//
//	mockgen -source client/http/accu_weather_client.go -destination client/http/mock/accu_weather_client.go
//

// Package mock_http is a generated GoMock package.
package mock_http

import (
	dto "github.com/shredd0r/weather-api/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccuWeatherInterface is a mock of AccuWeatherInterface interface.
type MockAccuWeatherInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccuWeatherInterfaceMockRecorder
}

// MockAccuWeatherInterfaceMockRecorder is the mock recorder for MockAccuWeatherInterface.
type MockAccuWeatherInterfaceMockRecorder struct {
	mock *MockAccuWeatherInterface
}

// NewMockAccuWeatherInterface creates a new mock instance.
func NewMockAccuWeatherInterface(ctrl *gomock.Controller) *MockAccuWeatherInterface {
	mock := &MockAccuWeatherInterface{ctrl: ctrl}
	mock.recorder = &MockAccuWeatherInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccuWeatherInterface) EXPECT() *MockAccuWeatherInterfaceMockRecorder {
	return m.recorder
}

// GetCurrentWeatherInfo mocks base method.
func (m *MockAccuWeatherInterface) GetCurrentWeatherInfo(request dto.AccuWeatherRequestDto) (*dto.AccuWeatherCurrentResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentWeatherInfo", request)
	ret0, _ := ret[0].(*dto.AccuWeatherCurrentResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentWeatherInfo indicates an expected call of GetCurrentWeatherInfo.
func (mr *MockAccuWeatherInterfaceMockRecorder) GetCurrentWeatherInfo(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentWeatherInfo", reflect.TypeOf((*MockAccuWeatherInterface)(nil).GetCurrentWeatherInfo), request)
}

// GetDailyWeatherInfo mocks base method.
func (m *MockAccuWeatherInterface) GetDailyWeatherInfo(request dto.AccuWeatherRequestDto) (*dto.AccuWeatherDailyResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyWeatherInfo", request)
	ret0, _ := ret[0].(*dto.AccuWeatherDailyResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyWeatherInfo indicates an expected call of GetDailyWeatherInfo.
func (mr *MockAccuWeatherInterfaceMockRecorder) GetDailyWeatherInfo(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyWeatherInfo", reflect.TypeOf((*MockAccuWeatherInterface)(nil).GetDailyWeatherInfo), request)
}

// GetGeoPositionSearch mocks base method.
func (m *MockAccuWeatherInterface) GetGeoPositionSearch(request dto.AccuWeatherGeoPositionRequestDto) (*dto.AccuWeatherGeoPositionResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeoPositionSearch", request)
	ret0, _ := ret[0].(*dto.AccuWeatherGeoPositionResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeoPositionSearch indicates an expected call of GetGeoPositionSearch.
func (mr *MockAccuWeatherInterfaceMockRecorder) GetGeoPositionSearch(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeoPositionSearch", reflect.TypeOf((*MockAccuWeatherInterface)(nil).GetGeoPositionSearch), request)
}

// GetHourlyWeatherInfo mocks base method.
func (m *MockAccuWeatherInterface) GetHourlyWeatherInfo(request dto.AccuWeatherRequestDto) (*[]dto.AccuWeatherHourlyResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHourlyWeatherInfo", request)
	ret0, _ := ret[0].(*[]dto.AccuWeatherHourlyResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHourlyWeatherInfo indicates an expected call of GetHourlyWeatherInfo.
func (mr *MockAccuWeatherInterfaceMockRecorder) GetHourlyWeatherInfo(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHourlyWeatherInfo", reflect.TypeOf((*MockAccuWeatherInterface)(nil).GetHourlyWeatherInfo), request)
}
