// Code generated by MockGen. DO NOT EDIT.
// Source: client/http/api_ninjas_client.go
//
// Generated by this command:
//
//	mockgen -source client/http/api_ninjas_client.go -destination client/http/mock/api_ninjas_client.go
//

// Package mock_http is a generated GoMock package.
package mock_http

import (
	dto "github.com/shredd0r/weather-api/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApiNinjasInterface is a mock of ApiNinjasInterface interface.
type MockApiNinjasInterface struct {
	ctrl     *gomock.Controller
	recorder *MockApiNinjasInterfaceMockRecorder
}

// MockApiNinjasInterfaceMockRecorder is the mock recorder for MockApiNinjasInterface.
type MockApiNinjasInterfaceMockRecorder struct {
	mock *MockApiNinjasInterface
}

// NewMockApiNinjasInterface creates a new mock instance.
func NewMockApiNinjasInterface(ctrl *gomock.Controller) *MockApiNinjasInterface {
	mock := &MockApiNinjasInterface{ctrl: ctrl}
	mock.recorder = &MockApiNinjasInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiNinjasInterface) EXPECT() *MockApiNinjasInterfaceMockRecorder {
	return m.recorder
}

// GetGeocoding mocks base method.
func (m *MockApiNinjasInterface) GetGeocoding(request dto.ApiNinjasGeocodingRequestDto) (*dto.ApiNinjasGeocodingResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeocoding", request)
	ret0, _ := ret[0].(*dto.ApiNinjasGeocodingResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeocoding indicates an expected call of GetGeocoding.
func (mr *MockApiNinjasInterfaceMockRecorder) GetGeocoding(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeocoding", reflect.TypeOf((*MockApiNinjasInterface)(nil).GetGeocoding), request)
}

// GetReversGeocoding mocks base method.
func (m *MockApiNinjasInterface) GetReversGeocoding(request dto.ApiNinjasReverseGeocodingRequestDto) (*dto.ApiNinjasReverseGeocodingResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReversGeocoding", request)
	ret0, _ := ret[0].(*dto.ApiNinjasReverseGeocodingResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReversGeocoding indicates an expected call of GetReversGeocoding.
func (mr *MockApiNinjasInterfaceMockRecorder) GetReversGeocoding(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReversGeocoding", reflect.TypeOf((*MockApiNinjasInterface)(nil).GetReversGeocoding), request)
}
