// Code generated by MockGen. DO NOT EDIT.
// Source: client/http/open_weather_client.go
//
// Generated by this command:
//
//	mockgen -source client/http/open_weather_client.go -destination client/http/mock/open_weather_client.go
//

// Package mock_http is a generated GoMock package.
package mock_http

import (
	dto "github.com/shredd0r/weather-api/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOpenWeatherInterface is a mock of OpenWeatherInterface interface.
type MockOpenWeatherInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOpenWeatherInterfaceMockRecorder
}

// MockOpenWeatherInterfaceMockRecorder is the mock recorder for MockOpenWeatherInterface.
type MockOpenWeatherInterfaceMockRecorder struct {
	mock *MockOpenWeatherInterface
}

// NewMockOpenWeatherInterface creates a new mock instance.
func NewMockOpenWeatherInterface(ctrl *gomock.Controller) *MockOpenWeatherInterface {
	mock := &MockOpenWeatherInterface{ctrl: ctrl}
	mock.recorder = &MockOpenWeatherInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenWeatherInterface) EXPECT() *MockOpenWeatherInterfaceMockRecorder {
	return m.recorder
}

// GetCurrentWeatherInfo mocks base method.
func (m *MockOpenWeatherInterface) GetCurrentWeatherInfo(request dto.OpenWeatherRequestDto) (*dto.OpenWeatherCurrentWeatherResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentWeatherInfo", request)
	ret0, _ := ret[0].(*dto.OpenWeatherCurrentWeatherResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentWeatherInfo indicates an expected call of GetCurrentWeatherInfo.
func (mr *MockOpenWeatherInterfaceMockRecorder) GetCurrentWeatherInfo(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentWeatherInfo", reflect.TypeOf((*MockOpenWeatherInterface)(nil).GetCurrentWeatherInfo), request)
}

// GetForecastWeatherInfo mocks base method.
func (m *MockOpenWeatherInterface) GetForecastWeatherInfo(request dto.OpenWeatherForecastRequestDto) (*dto.OpenWeatherHourlyWeatherResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForecastWeatherInfo", request)
	ret0, _ := ret[0].(*dto.OpenWeatherHourlyWeatherResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForecastWeatherInfo indicates an expected call of GetForecastWeatherInfo.
func (mr *MockOpenWeatherInterfaceMockRecorder) GetForecastWeatherInfo(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForecastWeatherInfo", reflect.TypeOf((*MockOpenWeatherInterface)(nil).GetForecastWeatherInfo), request)
}
